resource_manifest_version '44febabe-d386-4d18-afbe-5e627f4af937'

client_script = "discord.lua"

-- OVO JE SAMO ZA STARIJE SERVERE ZA FIVEM OD PRIJE 1.MJESECA 2020 GODINE
-- AKO IMATE SERVER OD TADA ONDA PROMIJENITE NAZIV OVOG FILEA U OVO ---> "__resource.lua"
-- POSLIJE TOGA SVE JE SPREMNO, ALI AKO DOBITE ERROR U KONZOLI ZA OVU SKRIPTU, ONDA IZBRISITE fxmanifest.lua, JER JE TAJ FILE ISTI KAO __resource.lua ALI JE ZA NOVIJE VERZIJE SERVERA
